insert into experts (
  code,
  full_name,
  degree,
  avatar_emoji,
  status,
  rating,
  sessions_count,
  satisfaction_rate,
  base_price,
  location,
  experience_years,
  specialties,
  tags,
  bio,
  credentials,
  approaches,
  next_slot_label,
  active,
  metadata
)
values
(
  'lan-anh',
  'ThS. Nguyễn Thị Lan Anh',
  'Thạc sĩ Tâm lý lâm sàng · ĐH Y Hà Nội',
  '👩‍⚕️',
  'online',
  4.9,
  248,
  97,
  350000,
  'Hà Nội',
  8,
  '["Lo âu","Trầm cảm","Stress công việc","Burnout"]'::jsonb,
  '["anxiety","depression","stress"]'::jsonb,
  'Chuyên gia tâm lý lâm sàng với 8 năm kinh nghiệm, từng công tác tại Viện Sức khỏe Tâm thần Quốc gia. Chuyên điều trị lo âu, trầm cảm và các rối loạn liên quan đến stress.',
  '["🎓 Thạc sĩ Tâm lý lâm sàng — ĐH Y Hà Nội (2016)","🏥 Chứng chỉ CBT — Beck Institute, Philadelphia (2018)","🌏 Chứng chỉ MBSR — ĐH Massachusetts (2020)","📜 Thành viên Hội Tâm lý học Việt Nam"]'::jsonb,
  '["Trị liệu Nhận thức Hành vi (CBT)","Chánh niệm (Mindfulness)","Trị liệu Chấp nhận và Cam kết (ACT)"]'::jsonb,
  'Hôm nay, 14:00',
  true,
  '{"featured":true}'::jsonb
),
(
  'van-minh',
  'TS. Trần Văn Minh',
  'Tiến sĩ Tâm lý học Giáo dục · ĐH Sư phạm',
  '👨‍⚕️',
  'online',
  4.8,
  512,
  96,
  500000,
  'TP. HCM',
  15,
  '["Mối quan hệ","Căng thẳng học đường","Trầm cảm","Gia đình"]'::jsonb,
  '["relationship","depression","stress"]'::jsonb,
  'Hơn 15 năm kinh nghiệm trong tư vấn tâm lý giáo dục và gia đình. TS Minh nổi tiếng với cách tiếp cận nhẹ nhàng, thấu hiểu và tập trung vào giải pháp.',
  '["🎓 Tiến sĩ Tâm lý học — ĐH Sư phạm TP.HCM","🏥 Chứng chỉ Trị liệu Hệ thống Gia đình — Úc","📜 Cố vấn cấp cao tại nhiều trung tâm tâm lý"]'::jsonb,
  '["Trị liệu Hệ thống","Trị liệu Tập trung vào Giải pháp (SFBT)","Tâm lý học Tích cực"]'::jsonb,
  'Hôm nay, 16:30',
  true,
  '{"featured":true}'::jsonb
),
(
  'hai-yen',
  'ThS. Lê Hải Yến',
  'Thạc sĩ Tâm lý · ĐH Monash (Úc)',
  '👩‍⚕️',
  'busy',
  5.0,
  186,
  98,
  450000,
  'Online / Hà Nội',
  6,
  '["Trauma","Mất ngủ","Lo âu","Self-esteem"]'::jsonb,
  '["trauma","sleep","anxiety"]'::jsonb,
  'Chuyên gia phục hồi sau sang chấn và các rối loạn giấc ngủ. Cô luôn tạo ra không gian an toàn tuyệt đối để khách hàng có thể mở lòng.',
  '["🎓 Thạc sĩ Tâm lý — Monash University","💤 Chứng nhận CBT-I cho rối loạn giấc ngủ","🛡️ Đào tạo chuyên sâu về trauma-informed care"]'::jsonb,
  '["Trauma-informed care","CBT-I","Somatic grounding"]'::jsonb,
  'Ngày mai, 09:00',
  true,
  '{"featured":false}'::jsonb
)
on conflict (code) do update
set
  full_name = excluded.full_name,
  degree = excluded.degree,
  avatar_emoji = excluded.avatar_emoji,
  status = excluded.status,
  rating = excluded.rating,
  sessions_count = excluded.sessions_count,
  satisfaction_rate = excluded.satisfaction_rate,
  base_price = excluded.base_price,
  location = excluded.location,
  experience_years = excluded.experience_years,
  specialties = excluded.specialties,
  tags = excluded.tags,
  bio = excluded.bio,
  credentials = excluded.credentials,
  approaches = excluded.approaches,
  next_slot_label = excluded.next_slot_label,
  active = excluded.active,
  metadata = excluded.metadata,
  updated_at = now();
